### ISSUE TITLE
URL seems to be outdated

### ISSUE THREAD

**Issue by reynir** [trygvis/intellij-idea-dpkg#36]
Since about a week ago `build-package` stopped working with the message "Unable to find the latest version."

    $ ./build-package -f IC -p debianSaving the flavor so you don't have to specify it again.
    Finding latest version from http://confluence.jetbrains.net/display/IDEADEV/IDEA+15+EAP ...
    Unable to find the latest version.

**Comment by trygvis** [comment]
It's not outdated, but they use a new pattern for the filenames. I'm not sure if I will support this as they sometimes have strange patterns. If you really want to build this giving -v PublicPreview should work. Note that the version in the package will also be PublicPreview.

**Comment by reynir** [comment]
It seems to be working again.
